name: Update Post
on:
  workflow_dispatch:
  schedule:
    # Run workflow every hour
    - cron: "0 * * * *"

env:
  account_id: ${{ secrets.ACCOUNT_ID }}
  authorization_key: ${{ secrets.AUTHORIZATION_KEY }}

defaults:
  run:
    working-directory: ./scripts

jobs:
  update_post:
    runs-on: ubuntu-latest
    steps:
      - name: Copy environment variables
        run: touch ./.env && printf "ACCOUNT_ID=${{ env.account_id }} \nAUTHORIZATION_KEY=${{ env.authorization_key }}\n" > ./.env
      - name: Run update script
        run: node ./get-instagram-post.js
