name: Update Post
on:
  workflow_dispatch:
  schedule:
    # Run workflow every hour
    - cron: "0 * * * *"

env:
  account_id: ${{ secrets.ACCOUNT_ID }}
  authorization_key: ${{ secrets.AUTHORIZATION_KEY }}

defaults:
  run:
    working-directory: scripts

jobs:
  update_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy environment variables
        run: touch .env && printf "ACCOUNT_ID=${{ env.account_id }} \nAUTHORIZATION_KEY=${{ env.authorization_key }}\n" > .env
      - name: Run update script
        run: node get-instagram-post.js
      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push to GitHub
        run: |
          git add .
          git commit -m "chore: update IG post"
          git push origin $BRANCH
